spring.application.name=barra
# URL de conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/barra

# Usuário e senha do banco
spring.datasource.username=postgres
spring.datasource.password=1234

# Driver JDBC do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Atualização automática do schema (opções: none, validate, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL gerado no console
spring.jpa.show-sql=true

#Upload de arquivos
app.upload.base-dir=upload